version: '3'

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - ex01-node_modules:/workspace/frontend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  ex01-node_modules:
